import { GameState } from '@/store/game/types';

export const QUESTIONS_MOCK: GameState['quiz'] = [
    {
        id: 1,
        question: "What is the capital of France?",
        options: ["Berlin", "Madrid", "Paris", "Rome"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 2,
        question: "Which planet is known as the Red Planet?",
        options: ["Venus", "Mars", "Jupiter", "Saturn"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 2,
    },
    {
        id: 3,
        question: "What is the largest ocean on Earth?",
        options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 4,
    },
    {
        id: 4,
        question: "Who wrote 'Romeo and Juliet'?",
        options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 2,
    },
    {
        id: 5,
        question: "What is the chemical symbol for gold?",
        options: ["Go", "Gd", "Au", "Ag"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 6,
        question: "Which country is known as the Land of the Rising Sun?",
        options: ["China", "Thailand", "Japan", "South Korea"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 7,
        question: "What is the square root of 144?",
        options: ["10", "11", "12", "13"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 8,
        question: "Which element has the atomic number 1?",
        options: ["Helium", "Hydrogen", "Lithium", "Beryllium"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 2,
    },
    {
        id: 9,
        question: "What is the capital of Australia?",
        options: ["Sydney", "Melbourne", "Canberra", "Perth"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 10,
        question: "Which programming language was created by Guido van Rossum?",
        options: ["Java", "C++", "Python", "JavaScript"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 11,
        question: "What is the value of π (pi) to two decimal places?",
        options: ["3.12", "3.14", "3.16", "3.18"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 2,
    },
    {
        id: 12,
        question: "Which philosopher is known for the theory of relativity?",
        options: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Niels Bohr"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 2,
    },
    {
        id: 13,
        question: "What is the most abundant gas in Earth's atmosphere?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 14,
        question: "Which novel begins with 'It was the best of times, it was the worst of times'?",
        options: ["Pride and Prejudice", "Great Expectations", "A Tale of Two Cities", "Oliver Twist"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 3,
    },
    {
        id: 15,
        question: "What is the derivative of sin(x) with respect to x?",
        options: ["cos(x)", "-sin(x)", "tan(x)", "sec(x)"],
        answeredOptionSerialNumber: null,
        correctOptionSerialNumber: 1,
    },
]