export const LANGUAGES = [
  'Armenian (Հայերեն)',
  'English',
  'Spanish (Español)',
  'French (Français)',
  'German (Deutsch)',
  'Italian (Italiano)',
  'Portuguese (Português)',
  'Portuguese - Brazil (Português — BR)',
  'Russian (Русский)',
  'Chinese — Simplified (简体中文)',
  'Chinese — Traditional (繁體中文)',
  'Japanese (日本語)',
  'Korean (한국어)',
  'Arabic (العربية)',
  'Hindi (हिन्दी)',
  'Persian / Farsi (فارسی)',
  'Vietnamese (Tiếng Việt)',
  'Thai (ไทย)',
  'Indonesian (Bahasa Indonesia)',
  'Polish (Polski)',
  'Dutch (Nederlands)',
  'Swedish (Svenska)',
  'Norwegian (Norsk)',
  'Danish (Dansk)',
  'Finnish (Suomi)',
  'Czech (Čeština)',
  'Slovak (Slovenčina)',
  'Hungarian (Magyar)',
  'Romanian (Română)',
  'Greek (Ελληνικά)',
  'Ukrainian (Українська)',
  'Bulgarian (Български)',
  'Serbian (Српски)',
  'Croatian (Hrvatski)',
  'Slovenian (Slovenščina)',
  'Latvian (Latviešu)',
  'Lithuanian (Lietuvių)',
  'Estonian (Eesti)',
  'Albanian (Shqip)',
  'Georgian (ქართული)',
  'Macedonian (Македонски)',
  'Filipino (Filipino / Tagalog)',
  'Nepali (नेपाली)',
  'Lao (ພາສາລາວ)',
]

export const DIFFICULTY_LEVELS = [
  'Very easy',
  'Easy',
  'Medium',
  'Hard',
  'Very hard',
]
