export const LANGUAGES = [
  'Armenian (Հայերեն)',
  'English',
  'Spanish (Español)',
  'French (Français)',
  'German (Deutsch)',
  'Italian (Italiano)',
  'Portuguese (Português)',
  'Portuguese - Brazil (Português — BR)',
  'Russian (Русский)',
  'Chinese — Simplified (简体中文)',
  'Chinese — Traditional (繁體中文)',
  'Japanese (日本語)',
  'Korean (한국어)',
  'Arabic (العربية)',
  'Hindi (हिन्दी)',
  'Bengali (বাংলা)',
  'Urdu (اردو)',
  'Persian / Farsi (فارسی)',
  'Turkish (Türkçe)',
  'Vietnamese (Tiếng Việt)',
  'Thai (ไทย)',
  'Indonesian (Bahasa Indonesia)',
  'Malay (Bahasa Melayu)',
  'Polish (Polski)',
  'Dutch (Nederlands)',
  'Swedish (Svenska)',
  'Norwegian (Norsk)',
  'Danish (Dansk)',
  'Finnish (Suomi)',
  'Czech (Čeština)',
  'Slovak (Slovenčina)',
  'Hungarian (Magyar)',
  'Romanian (Română)',
  'Greek (Ελληνικά)',
  'Hebrew (עברית)',
  'Ukrainian (Українська)',
  'Bulgarian (Български)',
  'Serbian (Српски)',
  'Croatian (Hrvatski)',
  'Slovenian (Slovenščina)',
  'Latvian (Latviešu)',
  'Lithuanian (Lietuvių)',
  'Estonian (Eesti)',
  'Albanian (Shqip)',
  'Georgian (ქართული)',
  'Macedonian (Македонски)',
  'Filipino (Filipino / Tagalog)',
  'Swahili (Kiswahili)',
  'Amharic (አማርኛ)',
  'Nepali (नेपाली)',
  'Sinhala (සිංහල)',
  'Khmer (ភាសាខ្មែរ)',
  'Lao (ພາສາລາວ)',
  'Burmese (မြန်မာ)',
]

export const DIFFICULTY_LEVELS = [
  'Very easy',
  'Easy',
  'Medium',
  'Hard',
  'Very hard',
]
